services:
  # DB
  alope-db:
    image: postgres:15-alpine
    container_name: alope_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alope-course
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend: Auth Service
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      alope-db:
        condition: service_healthy
    environment:
      - PORT=8081
      - DB_HOST=alope-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=alope-course

  # Backend: Course Service
  course-service:
    build: ./backend/course-service
    ports:
      - "8080:8080"
    depends_on:
      alope-db:
        condition: service_healthy
    environment:
      - PORT=8080
      - DB_HOST=alope-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=alope-course

  # Backend: CMS Service
  cms-service:
    build:
      context: ./backend/cms-service
      dockerfile: Dockerfile
    container_name: cms_service
    ports:
      - "8082:8082"
    depends_on:
      alope-db:
        condition: service_healthy
    environment:
      - PORT=8082
      - DB_HOST=alope-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=alope-course
      - DB_PORT=5432
      - DB_SSLMODE=disable

  # Frontend: Alope Course (Next.js)
  alope-course:
    build: ./frontend/alope-course
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1

  # Frontend: Alope Admin
  alope-admin:
    build: ./frontend/alope-admin
    ports:
      - "3001:80"
